email_from:
  address: addy1@email.com
  name: Tweet Digest - automated message
email-to:
  - addy1@email.com
  - addy2@email.com
email_server:
  server: localhost
  port: 25
  username:
  password:
consumer_key: "abc123"
consumer_secret: "abc123"
access_token: "abc123"
access_token_secret: "abc123"
